module.exports = {

  Sidebar: {
    Welcome: ['intro', 'discord',],
    "API": ['api-getting-started/intro', 'api-getting-started/authentication', 'api-getting-started/socket', 'api-getting-started/collections'],
    "API Reference": [
      {
        type: "category",
        label: "Simply Plural",
        link: {
          type: "generated-index",
          title: "Simply Plural API",
          description:
            "This is the reference for the Simply Plural API. All public endpoints are documented here and can be used to make API calls.",
          slug: "/docs/api"
        },
        // @ts-ignore
        items: require("./docs/api/sidebar.js")
      }
    ],
    "Docs":
    [
      {
        type: 'category',
        label: 'Help',
        link: {
          type: 'generated-index',
          title: 'Help',
          description: 'Help for all things Simply Plural.',
          slug: '/help',
        }
        ,
        items:[ 
          {
            type: 'category',
            label: 'Third Party Integrations',
            link: {
              type: 'generated-index',
              title: 'Third party integrations help',
              description: 'General help for third party integrations such as PluralKit',
              slug: '/help/third_party',
            },
            items: [
              {
                type: 'autogenerated',
                dirName: 'help/third_party', 
              },
            ],
          },
          {
          type: 'category',
          label: 'Account',
          link: {
            type: 'generated-index',
            title: 'Account Help',
            description: 'General help for all account related topics.',
            slug: '/help/account',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'help/account', 
            },
          ],
        },
        {
          type: 'category',
          label: 'Simply Plus',
          link: {
            type: 'generated-index',
            title: 'Simply Plural Help',
            description: 'Help for all Simply Plus related topics.',
            slug: '/help/plus',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'help/plus', 
            },
          ],
        }]
      }
    ]
  }
};
