import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

import apiSidebar from "./docs/api/sidebar";

const sidebars: SidebarsConfig = {

  Sidebar: {
    Welcome: ['intro', 'discord',],
    "API": ['api-getting-started/intro', 'api-getting-started/authentication', 'api-getting-started/socket', 'api-getting-started/collections'],
    "API Reference": [
      {
        type: "category",
        label: "Simply Plural",
        link: {
          type: "generated-index",
          title: "Simply Plural API",
          description:
            "This is the reference for the Simply Plural API. All public endpoints are documented here and can be used to make API calls.",
          slug: "/docs/api"
        },
        // @ts-ignore
        items: apiSidebar
      }
    ],
    "Docs":
    [
      {
        type: 'category',
        label: 'Help',
        link: {
          type: 'generated-index',
          title: 'Help',
          description: 'Help for all things Simply Plural.',
          slug: '/help',
        }
        ,
        items:[ 
         
          {
          type: 'category',
          label: 'Account',
          link: {
            type: 'generated-index',
            title: 'Account Help',
            description: 'General help for all account related topics.',
            slug: '/help/account',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'help/account', 
            },
          ],
        },
        {
          type: 'category',
          label: 'Features',
          link: {
            type: 'generated-index',
            title: 'Features Help',
            description: 'General help for features.',
            slug: '/help/features',
          },
          items: [
            {
              type: 'category',
              label: 'Archive',
              link: {
                type: 'generated-index',
                title: 'Archive Help',
                description: 'General help for archiving members',
                slug: '/help/features/archive',
              },
              items: [
                "help/features/archive/archive"
              ],
            },
            {
              type: 'category',
              label: 'Privacy Buckets',
              link: {
                type: 'generated-index',
                title: 'Privacy Buckets Help',
                description: 'General help for privacy buckets.',
                slug: '/help/features/buckets',
              },
              items: [
                "help/features/buckets/privacy_buckets",
                "help/features/buckets/add_bucket",
                "help/features/buckets/assign_bucket_to_content",
                "help/features/buckets/assign_bucket_to_friend",
              ],
            },
          ],
        },
       /* {
          type: 'category',
          label: 'Simply Plus',
          link: {
            type: 'generated-index',
            title: 'Simply Plural Help',
            description: 'Help for all Simply Plus related topics.',
            slug: '/help/plus',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'help/plus', 
            },
          ],
        },*/
        {
          type: 'category',
          label: 'Third Party Integrations',
          link: {
            type: 'generated-index',
            title: 'Third party integrations help',
            description: 'General help for third party integrations such as PluralKit',
            slug: '/help/third_party',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'help/third_party', 
            },
          ],
        },]
      }
    ]
  }
};

export default sidebars;