openapi: "3.0.2"
info:
  title: Simply Plural API
  description: This API reference documents the public api endpoints. You can see a list of all public endpoints here https://github.com/ApparyllisOrg/SimplyPluralApi/blob/release/src/api/v1/routes.ts
  version: "1.0"

paths:
  /somePath:
    get:
      responses:
        200:
          description: ok

components:
  schemas:
    commons:
      type: object
      properties:
        systemId:
          description: The system Id
        color:
          description: Color of the object (\#ffffff, \#ffffffff or ffffff)
        private:
          description: Whether this object is private
        preventTrusted:
          description: Wheter trusted friends are prevented from seeing this private object
        supportDescMarkdown:
          description: Whether the description supports markdown
        timestamp:
          description: Milliseconds since epoch for this timestamp/date
        lastOperationTime:
          description: Time in milliseconds since epoch of the last operation on this object

  parameters:
    objectId:
      - in: path
        name: id
        required: true
        description: Id of the object, this can be a mongo Id but also a plain string (backwards-compatibility).
        schema:
          type: string
