openapi: "3.0.2"
info:
  title: Simply Plural API
  description: This API reference documents the public api endpoints. You can see a list of all public endpoints here https://github.com/ApparyllisOrg/SimplyPluralApi/blob/release/src/api/v1/routes.ts
  version: "1.0"

components:
  schemas:
    commons:
      type: object
      properties:
        color:
          description: 'Color of the object in a hex format (eg: \#ffffff, \#ffffffff or ffffff)'
        private:
          description: Whether this object is private
        preventTrusted:
          description: Wheter trusted friends are prevented from seeing this private object
        supportDescMarkdown:
          description: Whether the description supports markdown
        timestamp:
          description: Time in Milliseconds since epoch
        uid:
          description: The user Id of the system
        lastOperationTime:
          description: Time in milliseconds since epoch of the last update on this object

  parameters:
    friendId:
      - in: path
        name: friendId
        required: true
        description: Username or user Id or system ID of the friend
        schema:
          type: string
    objectId:
      - in: path
        name: id
        required: true
        description: Id of the object, this can be a mongo Id but also a plain string (backwards-compatibility).
        schema:
          type: string
    objectIdOptional:
      - in: path
        name: id
        required: false
        description: Optional Id of the object. If supplied, this must be a mongodb objectID format. If not supplied, the API will generate the id for you.
        schema:
          type: string
    systemId:
      - in: path
        name: systemId
        required: true
        description: The user Id of the system
        schema:
          type: string
    systemIdAndObjectId:
      - in: path
        name: systemId
        required: true
        description: The user Id of the system
        schema:
          type: string
      - in: path
        name: id
        required: true
        description: Id of the object, this can be a mongo Id but also a plain string (backwards-compatibility).
        schema:
          type: string
    username:
      - in: path
        name: Username
        required: true
        description: Username or user Id or system ID
        schema:
          type: string
